FROM python:3

WORKDIR /usr/src/app

COPY ./Docker/requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY ./Worker .

CMD [ "python", "./worker.py" ]